set(GLFW_PATH "D:/hehe/haha/glfw")
set(GLM_PATH "D:/hehe/haha/glm")
set(VULKAN_SDK_PATH  "D:/hehe/haha/VulkanSDK")
set(BOOST_ROOT  "D:/hehe/haha/boost_1_84_0")
set(CPPLINT_PATH  "D:/hehe/haha/Python/Scripts")
